-- "Did You Know?" factoids per celestial object
CREATE TABLE factoids (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  object_id TEXT NOT NULL REFERENCES celestial_objects(id),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_factoids_object_id ON factoids(object_id);
ALTER TABLE factoids ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Factoids are viewable by everyone" ON factoids FOR SELECT USING (true);

-- Sun
INSERT INTO factoids (object_id, content) VALUES
('sun', 'The Sun contains 99.86% of all the mass in the solar system.'),
('sun', 'Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.'),
('sun', 'The Sun''s core temperature is approximately 15 million degrees Celsius.'),
('sun', 'About 1.3 million Earths could fit inside the Sun.'),
('sun', 'The Sun rotates faster at its equator (25 days) than at its poles (35 days).'),
('sun', 'The Sun converts about 600 million tonnes of hydrogen into helium every second.'),
('sun', 'The Sun is roughly halfway through its 10-billion-year lifespan.'),
('sun', 'Solar flares can release the energy equivalent of millions of nuclear bombs in minutes.'),
('sun', 'The Sun''s magnetic field reverses polarity approximately every 11 years.'),
('sun', 'The surface of the Sun (photosphere) is about 5,500 °C — cooler than many welding arcs.'),
('sun', 'The Sun loses about 4 million tonnes of mass per second through nuclear fusion.'),
('sun', 'Solar wind travels at 400–750 km/s and reaches the edge of the solar system.'),
('sun', 'The Sun''s corona is hundreds of times hotter than its surface — a mystery still being studied.'),
('sun', 'The Sun produces enough energy in one second to power Earth for 500,000 years.'),
('sun', 'Sunspots are cooler regions on the surface, about 1,500 °C below the surrounding area.'),
('sun', 'The Sun''s gravitational pull holds the entire solar system together, out to the Oort Cloud.'),
('sun', 'The Sun is a nearly perfect sphere — its equatorial and polar diameters differ by only 10 km.'),
('sun', 'Ancient Egyptians worshipped the Sun god Ra, one of the earliest recorded solar deities.'),
('sun', 'The Sun''s photons take about 170,000 years to travel from the core to the surface.'),
('sun', 'Total solar eclipses are possible because the Sun and Moon appear almost exactly the same size from Earth.'),
('sun', 'The Sun orbits the centre of the Milky Way at about 828,000 km/h.'),
('sun', 'It takes the Sun about 225–250 million years to complete one galactic orbit.'),
('sun', 'The Sun is classified as a yellow dwarf (G2V) star, though it actually appears white from space.'),
('sun', 'The solar wind creates the heliosphere, a bubble that shields the solar system from interstellar radiation.'),
('sun', 'Neutrinos produced in the Sun''s core pass through Earth — about 100 billion through your thumbnail each second.'),
('sun', 'The Sun is about 4.6 billion years old, formed from a cloud of gas and dust.'),
('sun', 'During a total solar eclipse, the Sun''s corona becomes visible as a pearly white halo.'),
('sun', 'The Sun''s luminosity has increased by about 30% since it first formed.'),
('sun', 'Solar prominences are loops of plasma that can extend hundreds of thousands of kilometres into space.'),
('sun', 'The closest star system to the Sun is Alpha Centauri, about 4.37 light-years away.');

-- Mercury
INSERT INTO factoids (object_id, content) VALUES
('mercury', 'Mercury is the smallest planet in the solar system, only slightly larger than Earth''s Moon.'),
('mercury', 'A day on Mercury (sunrise to sunrise) lasts 176 Earth days.'),
('mercury', 'Mercury has the most extreme temperature swings: from 430 °C in daytime to −180 °C at night.'),
('mercury', 'Despite being closest to the Sun, Mercury is not the hottest planet — Venus is.'),
('mercury', 'Mercury has no moons and no rings.'),
('mercury', 'Mercury''s orbit is the most eccentric (oval-shaped) of all the planets.'),
('mercury', 'The Caloris Basin on Mercury is one of the largest impact craters in the solar system, about 1,550 km wide.'),
('mercury', 'Mercury has a massive iron core that makes up about 75% of the planet''s radius.'),
('mercury', 'A year on Mercury is only 88 Earth days — the shortest of any planet.'),
('mercury', 'Mercury has been visited by only two spacecraft: Mariner 10 and MESSENGER.'),
('mercury', 'Mercury''s surface looks remarkably similar to Earth''s Moon, covered in craters.'),
('mercury', 'Mercury has a very thin exosphere made of atoms blasted off its surface by solar wind.'),
('mercury', 'Ice exists in permanently shadowed craters at Mercury''s poles despite the extreme heat.'),
('mercury', 'Mercury''s surface gravity is about 38% of Earth''s — you''d weigh much less there.'),
('mercury', 'The planet is named after the Roman messenger god due to its fast orbit.'),
('mercury', 'Mercury shrinks as its iron core cools, causing wrinkle-like scarps across its surface.'),
('mercury', 'Mercury can be seen from Earth with the naked eye, best at dawn or dusk.'),
('mercury', 'Because Mercury orbits inside Earth''s orbit, it shows phases like the Moon when viewed through a telescope.'),
('mercury', 'A 68 kg person would weigh only about 26 kg on Mercury.'),
('mercury', 'Mercury''s magnetic field is about 1% as strong as Earth''s, but it still deflects solar wind.'),
('mercury', 'BepiColombo, a joint ESA/JAXA mission, is currently en route to Mercury.'),
('mercury', 'Mercury has virtually no atmosphere to distribute heat, causing its extreme temperature range.'),
('mercury', 'At perihelion, Mercury is only 46 million km from the Sun.'),
('mercury', 'Mercury completes three rotations for every two orbits around the Sun — a 3:2 spin-orbit resonance.'),
('mercury', 'Mercury''s density is the second highest in the solar system, after Earth.'),
('mercury', 'MESSENGER discovered that Mercury has a tail of sodium atoms blown back by solar wind.'),
('mercury', 'Ancient civilisations thought Mercury was two separate objects — a morning star and an evening star.'),
('mercury', 'Mercury''s thin exosphere contains hydrogen, helium, oxygen, sodium, and potassium.'),
('mercury', 'The MESSENGER spacecraft orbited Mercury for four years before crashing into its surface in 2015.'),
('mercury', 'Mercury transits across the face of the Sun about 13 times per century as seen from Earth.');

-- Venus
INSERT INTO factoids (object_id, content) VALUES
('venus', 'Venus is the hottest planet in the solar system, with surface temperatures around 465 °C.'),
('venus', 'Venus rotates backwards compared to most planets — the Sun rises in the west and sets in the east.'),
('venus', 'A day on Venus (243 Earth days) is longer than its year (225 Earth days).'),
('venus', 'Venus''s thick atmosphere is 96% carbon dioxide, creating a runaway greenhouse effect.'),
('venus', 'Atmospheric pressure on Venus''s surface is about 90 times that of Earth.'),
('venus', 'Venus is often called Earth''s twin because of their similar size and mass.'),
('venus', 'Venus has no moons and no rings.'),
('venus', 'Venus is the brightest natural object in the night sky after the Moon.'),
('venus', 'The surface of Venus is hidden beneath thick clouds of sulphuric acid.'),
('venus', 'Soviet Venera probes were the first spacecraft to land on another planet — surviving only minutes.'),
('venus', 'Venus has over 1,600 major volcanoes, more than any other planet in the solar system.'),
('venus', 'Radar mapping by Magellan revealed that about 80% of Venus is covered by smooth volcanic plains.'),
('venus', 'Venus and Earth are sometimes called sister planets, though conditions are vastly different.'),
('venus', 'Wind speeds at Venus''s cloud tops reach 360 km/h, circling the planet in just 4 days.'),
('venus', 'Maxwell Montes is the highest mountain on Venus, rising about 11 km above the mean surface level.'),
('venus', 'Venus has a weak magnetic field, likely because it rotates too slowly to generate a strong dynamo.'),
('venus', 'Lightning has been detected in Venus''s atmosphere by multiple spacecraft.'),
('venus', 'In 2020, phosphine gas was tentatively detected in Venus''s clouds, sparking debate about possible life.'),
('venus', 'Venus is named after the Roman goddess of love and beauty.'),
('venus', 'The surface of Venus is relatively young — about 300–600 million years old based on crater counts.'),
('venus', 'Venus has pancake-shaped volcanic domes found nowhere else in the solar system.'),
('venus', 'A person standing on Venus would be crushed by the pressure, dissolved by the acid, and baked by the heat.'),
('venus', 'Venus''s cloud layers extend from about 45 to 70 km above the surface.'),
('venus', 'Venus approaches closer to Earth than any other planet — within about 38 million km.'),
('venus', 'The first successful flyby of another planet was Mariner 2''s pass of Venus in 1962.'),
('venus', 'Venus reflects about 70% of sunlight, making it extremely bright but hiding its surface.'),
('venus', 'If Venus had Earth''s rotation rate, it might have developed oceans and a very different climate.'),
('venus', 'Ancient civilisations called Venus both the Morning Star and the Evening Star.'),
('venus', 'Venus''s backward rotation may be the result of a massive ancient collision.'),
('venus', 'NASA''s DAVINCI and VERITAS missions are planned to study Venus in the 2030s.');

-- Earth
INSERT INTO factoids (object_id, content) VALUES
('earth', 'Earth is the only known planet to have liquid water on its surface.'),
('earth', 'Earth''s atmosphere is 78% nitrogen and 21% oxygen, with trace amounts of other gases.'),
('earth', 'Earth''s magnetic field protects life from harmful solar radiation and cosmic rays.'),
('earth', 'About 71% of Earth''s surface is covered by water.'),
('earth', 'Earth is the densest planet in the solar system at 5.51 g/cm³.'),
('earth', 'The Moon is slowly moving away from Earth at about 3.8 cm per year.'),
('earth', 'Earth''s inner core is as hot as the surface of the Sun — about 5,400 °C.'),
('earth', 'A year on Earth is actually 365.25 days, which is why we have leap years.'),
('earth', 'Earth''s rotation is gradually slowing — days were about 22 hours long 600 million years ago.'),
('earth', 'The deepest point on Earth is the Mariana Trench at about 11 km below sea level.'),
('earth', 'Earth is the only planet not named after a Greek or Roman deity.'),
('earth', 'Earth''s tilt of 23.5° gives us our seasons.'),
('earth', 'Plate tectonics make Earth unique — no other planet has this geological process.'),
('earth', 'The oldest rocks on Earth are about 4 billion years old, found in Canada.'),
('earth', 'Earth''s ozone layer absorbs 97–99% of the Sun''s ultraviolet radiation.'),
('earth', 'Mount Everest is 8,849 m tall, but Mauna Kea from base to peak is over 10,000 m.'),
('earth', 'Earth''s Van Allen belts trap charged particles and protect the surface from radiation.'),
('earth', 'The driest place on Earth is the Atacama Desert in Chile — some areas haven''t seen rain in centuries.'),
('earth', 'If Earth were the size of a basketball, the Moon would be a tennis ball about 7 metres away.'),
('earth', 'Earth''s circumference at the equator is about 40,075 km.'),
('earth', 'Lightning strikes Earth about 100 times every second.'),
('earth', 'Earth orbits the Sun at about 107,000 km/h.'),
('earth', 'The oldest living organisms on Earth are bristlecone pines, some over 5,000 years old.'),
('earth', 'Earth is about 4.54 billion years old.'),
('earth', 'The Aurora Borealis and Aurora Australis are caused by solar wind interacting with Earth''s magnetosphere.'),
('earth', 'Earth''s oceans contain about 1.335 billion cubic kilometres of water.'),
('earth', 'The tallest mountain in the solar system measured from base to peak might actually be on Earth — Mauna Kea.'),
('earth', 'About 8.7 million species are estimated to live on Earth, with many still undiscovered.'),
('earth', 'Earth is gradually getting warmer — the 10 warmest years on record have all occurred since 2010.'),
('earth', 'From space, Earth''s most prominent feature is the blue colour of its oceans.');

-- Mars
INSERT INTO factoids (object_id, content) VALUES
('mars', 'Mars has the tallest volcano in the solar system: Olympus Mons, at about 22 km high.'),
('mars', 'Valles Marineris on Mars is a canyon system 4,000 km long — nearly the width of Australia.'),
('mars', 'A day on Mars (called a sol) is 24 hours and 37 minutes — very close to Earth''s.'),
('mars', 'Mars has two small moons, Phobos and Deimos, likely captured asteroids.'),
('mars', 'Mars appears red because its surface is rich in iron oxide (rust).'),
('mars', 'Mars has seasons like Earth because of its 25° axial tilt.'),
('mars', 'Mars has the largest dust storms in the solar system, sometimes engulfing the entire planet.'),
('mars', 'Evidence of ancient river valleys and lake beds suggests Mars once had flowing water.'),
('mars', 'Mars has polar ice caps made of water ice and dry ice (frozen CO₂).'),
('mars', 'Phobos is slowly spiralling inward and will crash into Mars or break apart in about 50 million years.'),
('mars', 'Mars''s atmosphere is 95% carbon dioxide and less than 1% as dense as Earth''s.'),
('mars', 'The Curiosity rover has been exploring Mars since August 2012.'),
('mars', 'Mars''s gravity is about 38% of Earth''s — you could jump nearly three times higher.'),
('mars', 'Sunsets on Mars appear blue due to fine dust scattering light differently than on Earth.'),
('mars', 'Mars is about half the diameter of Earth.'),
('mars', 'The first successful Mars flyby was Mariner 4 in 1965, returning 22 close-up photos.'),
('mars', 'Mars has no global magnetic field, which allowed the solar wind to strip away most of its atmosphere.'),
('mars', 'A year on Mars is about 687 Earth days.'),
('mars', 'NASA''s Ingenuity helicopter achieved the first powered flight on another planet in April 2021.'),
('mars', 'Mars is named after the Roman god of war because of its blood-red appearance.'),
('mars', 'The Perseverance rover is collecting rock samples for future return to Earth.'),
('mars', 'Temperature on Mars ranges from about −140 °C in winter to 20 °C in summer at the equator.'),
('mars', 'Mars has auroras, but they occur at random locations because it lacks a global magnetic field.'),
('mars', 'Olympus Mons is so large that you wouldn''t see its peak from its base — it extends beyond the horizon.'),
('mars', 'The two moons of Mars are named after the sons of Ares (Greek god of war): Fear and Dread.'),
('mars', 'Liquid water may still exist underground on Mars today.'),
('mars', 'Mars has been the target of over 50 missions, with about half succeeding.'),
('mars', 'The thin atmosphere on Mars means the sky pressure is similar to 35 km altitude on Earth.'),
('mars', 'Mars has about 1/10th the mass of Earth.'),
('mars', 'Recurring slope lineae on Mars may be evidence of seasonal briny water flows.');

-- Jupiter
INSERT INTO factoids (object_id, content) VALUES
('jupiter', 'Jupiter is the largest planet in the solar system — over 1,300 Earths could fit inside it.'),
('jupiter', 'Jupiter''s Great Red Spot is a storm larger than Earth that has raged for at least 350 years.'),
('jupiter', 'Jupiter has at least 95 known moons.'),
('jupiter', 'A day on Jupiter is only about 10 hours — the shortest of any planet.'),
('jupiter', 'Jupiter''s magnetic field is about 20,000 times stronger than Earth''s.'),
('jupiter', 'Jupiter radiates more heat than it receives from the Sun.'),
('jupiter', 'Jupiter''s moon Europa likely has a subsurface ocean with more water than all of Earth''s oceans.'),
('jupiter', 'The Galilean moons (Io, Europa, Ganymede, Callisto) were discovered by Galileo in 1610.'),
('jupiter', 'Jupiter acts as a cosmic vacuum cleaner, deflecting many asteroids and comets from the inner solar system.'),
('jupiter', 'Jupiter has a faint ring system, discovered by Voyager 1 in 1979.'),
('jupiter', 'Io, Jupiter''s innermost large moon, is the most volcanically active body in the solar system.'),
('jupiter', 'Jupiter is a gas giant with no solid surface — it''s mostly hydrogen and helium.'),
('jupiter', 'If Jupiter were about 80 times more massive, it would have become a star.'),
('jupiter', 'Jupiter''s atmosphere has bands of clouds travelling in opposite directions at hundreds of km/h.'),
('jupiter', 'Wind speeds on Jupiter can reach up to 620 km/h.'),
('jupiter', 'The Juno spacecraft has been orbiting Jupiter since 2016, studying its interior and atmosphere.'),
('jupiter', 'Jupiter''s Great Red Spot has been shrinking over the past century.'),
('jupiter', 'Jupiter has the strongest radiation belts of any planet — lethal to unshielded humans.'),
('jupiter', 'Comet Shoemaker-Levy 9 crashed into Jupiter in 1994, leaving Earth-sized scars.'),
('jupiter', 'Jupiter can be seen with the naked eye and is usually the fourth-brightest object in the sky.'),
('jupiter', 'Jupiter''s core may be a dense mix of metallic hydrogen, rock, and ice.'),
('jupiter', 'The planet is named after the king of the Roman gods.'),
('jupiter', 'Jupiter takes about 12 Earth years to complete one orbit around the Sun.'),
('jupiter', 'Lightning on Jupiter is far more powerful than lightning on Earth.'),
('jupiter', 'Jupiter''s rapid rotation causes it to bulge at the equator — it''s visibly oblate.'),
('jupiter', 'Ganymede, Jupiter''s largest moon, is bigger than the planet Mercury.'),
('jupiter', 'Jupiter''s atmosphere contains trace amounts of ammonia, methane, and water vapour.'),
('jupiter', 'The Pioneer 10 spacecraft made the first close flyby of Jupiter in 1973.'),
('jupiter', 'Jupiter''s mass is 2.5 times that of all the other planets combined.'),
('jupiter', 'Metallic hydrogen deep inside Jupiter conducts electricity and generates its huge magnetic field.');

-- Saturn
INSERT INTO factoids (object_id, content) VALUES
('saturn', 'Saturn''s rings are made mostly of ice particles, with some rocky debris and dust.'),
('saturn', 'Saturn is the least dense planet in the solar system — it would float in a large enough bathtub.'),
('saturn', 'Saturn has at least 146 known moons, more than any other planet.'),
('saturn', 'Saturn''s rings span up to 282,000 km but are only about 10 metres thick in most places.'),
('saturn', 'A day on Saturn is about 10.7 hours.'),
('saturn', 'Saturn''s moon Titan has a thick atmosphere and liquid methane lakes on its surface.'),
('saturn', 'Enceladus, a moon of Saturn, shoots geysers of water ice into space from its south pole.'),
('saturn', 'Saturn''s hexagonal storm at its north pole is a unique weather pattern not seen elsewhere.'),
('saturn', 'Wind speeds on Saturn can exceed 1,800 km/h near its equator.'),
('saturn', 'Saturn''s rings may be relatively young — possibly only 100–400 million years old.'),
('saturn', 'The Cassini spacecraft orbited Saturn for 13 years (2004–2017) before plunging into its atmosphere.'),
('saturn', 'Saturn is about 9.5 times wider than Earth.'),
('saturn', 'Saturn''s rings are named alphabetically in the order they were discovered, not by distance.'),
('saturn', 'You could fit 764 Earths inside Saturn.'),
('saturn', 'Saturn takes about 29.5 Earth years to orbit the Sun.'),
('saturn', 'Titan is the only moon in the solar system with a substantial atmosphere.'),
('saturn', 'Saturn is named after the Roman god of agriculture and time.'),
('saturn', 'The Cassini division is a 4,800 km gap in Saturn''s rings caused by the moon Mimas''s gravity.'),
('saturn', 'Saturn''s density is only about 0.69 g/cm³ — less than water.'),
('saturn', 'Galileo first observed Saturn''s rings in 1610 but thought they were "ears" or companion bodies.'),
('saturn', 'Saturn''s magnetic field is about 578 times more powerful than Earth''s.'),
('saturn', 'Saturn radiates about 2.5 times more energy than it receives from the Sun.'),
('saturn', 'The Huygens probe landed on Titan in 2005 — the most distant landing ever achieved.'),
('saturn', 'Saturn''s rings are thought to be the remains of comets, asteroids, or moons that were torn apart.'),
('saturn', 'Enceladus''s subsurface ocean makes it one of the best candidates for finding extraterrestrial life.'),
('saturn', 'Saturn has a visible ring system that can be seen from Earth with a small telescope.'),
('saturn', 'The F ring of Saturn is braided and kinked by the gravitational influence of two shepherd moons.'),
('saturn', 'Saturn''s rotation is so fast that it is visibly flattened at the poles.'),
('saturn', 'Titan''s surface pressure is about 1.5 times Earth''s, despite being much smaller.'),
('saturn', 'Saturn''s largest moon Titan is bigger than Mercury.');

-- Uranus
INSERT INTO factoids (object_id, content) VALUES
('uranus', 'Uranus rotates on its side with an axial tilt of 98° — likely from an ancient massive collision.'),
('uranus', 'Uranus is an ice giant, composed mainly of water, methane, and ammonia ices.'),
('uranus', 'Uranus was the first planet discovered with a telescope, by William Herschel in 1781.'),
('uranus', 'A year on Uranus is about 84 Earth years.'),
('uranus', 'Uranus has 27 known moons, all named after characters from Shakespeare and Alexander Pope.'),
('uranus', 'Uranus has 13 known rings, which are very dark and narrow.'),
('uranus', 'Uranus''s blue-green colour comes from methane in its atmosphere absorbing red light.'),
('uranus', 'Uranus has the coldest atmosphere of any planet, with temperatures dropping to −224 °C.'),
('uranus', 'Because of its extreme tilt, Uranus has seasons that last about 21 years each.'),
('uranus', 'Uranus was nearly named "Georgium Sidus" (George''s Star) after King George III.'),
('uranus', 'Voyager 2 is the only spacecraft to have visited Uranus, flying by in January 1986.'),
('uranus', 'Uranus''s magnetic field is tilted 59° from its rotational axis — highly unusual.'),
('uranus', 'A day on Uranus is about 17 hours and 14 minutes.'),
('uranus', 'Uranus is about 4 times wider than Earth.'),
('uranus', 'At certain times, one pole of Uranus points almost directly at the Sun for 21 years.'),
('uranus', 'Uranus''s five largest moons are Miranda, Ariel, Umbriel, Titania, and Oberon.'),
('uranus', 'Miranda, a moon of Uranus, has one of the tallest cliffs in the solar system — Verona Rupes, about 20 km high.'),
('uranus', 'Uranus is named after the Greek god of the sky.'),
('uranus', 'Uranus and Neptune are sometimes called the "ice giant" planets, distinct from gas giants.'),
('uranus', 'Uranus has a mass about 14.5 times that of Earth.'),
('uranus', 'The interior of Uranus may contain a sea of water, ammonia, and other volatiles.'),
('uranus', 'Wind speeds on Uranus can reach up to 900 km/h.'),
('uranus', 'Uranus appears almost featureless in visible light, but infrared reveals cloud bands.'),
('uranus', 'Uranus''s rings were discovered in 1977 when they blocked light from a background star.'),
('uranus', 'If you fell into Uranus, you''d encounter increasingly dense and hot layers of gas and liquid.'),
('uranus', 'Uranus is about 2.9 billion km from the Sun.'),
('uranus', 'Diamond rain may occur deep inside Uranus where extreme pressure crystallises carbon.'),
('uranus', 'Uranus is just barely visible to the naked eye under perfect conditions.'),
('uranus', 'A proposed NASA mission called Uranus Orbiter and Probe could launch in the 2030s.'),
('uranus', 'Uranus takes about 17 hours to rotate once — similar to Neptune.');

-- Neptune
INSERT INTO factoids (object_id, content) VALUES
('neptune', 'Neptune has the fastest winds in the solar system, reaching speeds up to 2,100 km/h.'),
('neptune', 'Neptune was the first planet found by mathematical prediction rather than observation.'),
('neptune', 'A year on Neptune is about 165 Earth years — it completed its first full orbit since discovery in 2011.'),
('neptune', 'Neptune''s deep blue colour comes from methane absorbing red light.'),
('neptune', 'Neptune has 16 known moons, the largest being Triton.'),
('neptune', 'Triton orbits Neptune backwards (retrograde), suggesting it was captured from the Kuiper Belt.'),
('neptune', 'Neptune has a faint ring system with five main rings.'),
('neptune', 'Neptune radiates about 2.6 times more energy than it receives from the Sun.'),
('neptune', 'Voyager 2 is the only spacecraft to have visited Neptune, flying by in August 1989.'),
('neptune', 'The Great Dark Spot observed by Voyager 2 was a storm the size of Earth that has since disappeared.'),
('neptune', 'Neptune is about 4.5 billion km from the Sun — 30 times farther than Earth.'),
('neptune', 'Neptune is the most distant planet from the Sun since Pluto was reclassified in 2006.'),
('neptune', 'Neptune has a mass about 17 times that of Earth.'),
('neptune', 'A day on Neptune is about 16 hours.'),
('neptune', 'Neptune is named after the Roman god of the sea.'),
('neptune', 'Triton has geysers that shoot nitrogen gas up to 8 km above its surface.'),
('neptune', 'Neptune''s atmosphere is mainly hydrogen, helium, and methane.'),
('neptune', 'Neptune is about 3.9 times wider than Earth.'),
('neptune', 'Neptune was discovered in 1846 by Johann Galle, based on predictions by Urbain Le Verrier.'),
('neptune', 'Triton is one of the coldest objects in the solar system, with surface temperatures of −235 °C.'),
('neptune', 'Neptune''s magnetic field is tilted 47° from its rotational axis.'),
('neptune', 'Neptune has distinct cloud bands and storm systems visible in Hubble images.'),
('neptune', 'Triton will eventually spiral too close to Neptune and be torn apart, possibly forming a new ring.'),
('neptune', 'Neptune''s ring arcs are clumps of material within the Adams ring, held in place by the moon Galatea.'),
('neptune', 'Neptune''s interior may contain a mantle of water, methane, and ammonia ices.'),
('neptune', 'Diamond rain likely occurs inside Neptune, similar to Uranus.'),
('neptune', 'Sunlight takes about 4 hours to reach Neptune.'),
('neptune', 'Neptune''s discovery confirmed Newton''s law of gravitation applied even to distant objects.'),
('neptune', 'Neptune has been observed to have seasonal changes despite its extreme distance from the Sun.'),
('neptune', 'Neptune''s largest moon Triton is one of the few moons with a thin atmosphere.');

-- Moon
INSERT INTO factoids (object_id, content) VALUES
('moon', 'The Moon is about 384,400 km from Earth on average.'),
('moon', 'The Moon is the fifth-largest natural satellite in the solar system.'),
('moon', 'The same side of the Moon always faces Earth due to tidal locking.'),
('moon', 'The Moon has no atmosphere, so footprints left by astronauts could last millions of years.'),
('moon', 'Twelve people have walked on the Moon, all between 1969 and 1972.'),
('moon', 'The Moon''s gravity is about 1/6th of Earth''s.'),
('moon', 'The Moon causes most of Earth''s ocean tides through its gravitational pull.'),
('moon', 'The Moon is slowly moving away from Earth at about 3.8 cm per year.'),
('moon', 'The Moon formed about 4.5 billion years ago, likely from debris after a Mars-sized object hit Earth.'),
('moon', 'The dark patches on the Moon, called maria, are ancient lava flows.'),
('moon', 'Temperature on the Moon ranges from 127 °C in sunlight to −173 °C in shadow.'),
('moon', 'The Moon has water ice in permanently shadowed craters at its poles.'),
('moon', 'The Moon''s diameter is about 3,474 km — roughly the width of Australia.'),
('moon', 'Apollo 11 landed on the Moon on July 20, 1969, with Neil Armstrong and Buzz Aldrin.'),
('moon', 'Moonquakes, detected by Apollo seismometers, can last up to an hour due to lack of water to dampen vibrations.');

-- Titan
INSERT INTO factoids (object_id, content) VALUES
('titan', 'Titan is the only moon in the solar system with a dense, planet-like atmosphere.'),
('titan', 'Titan''s atmosphere is about 95% nitrogen, similar in composition to early Earth.'),
('titan', 'Titan has lakes and seas of liquid methane and ethane on its surface.'),
('titan', 'Titan''s surface pressure is about 1.5 times that of Earth''s.'),
('titan', 'The Huygens probe landed on Titan in January 2005, sending back the first images of its surface.'),
('titan', 'Titan''s surface temperature is about −179 °C.'),
('titan', 'Titan has a methane cycle similar to Earth''s water cycle, with rain, rivers, and lakes.'),
('titan', 'Titan is larger than the planet Mercury.'),
('titan', 'Titan''s thick haze prevented scientists from seeing its surface until Cassini arrived with radar.'),
('titan', 'NASA''s Dragonfly mission will send a drone to fly around Titan, planned for arrival in the 2030s.'),
('titan', 'Titan''s largest sea, Kraken Mare, is about 400,000 km² — larger than the Caspian Sea.'),
('titan', 'Titan may have a subsurface ocean of liquid water beneath its icy crust.'),
('titan', 'Titan''s orange colour comes from complex organic molecules called tholins in its atmosphere.'),
('titan', 'Titan''s gravity is about 14% of Earth''s — a human could strap on wings and fly.'),
('titan', 'Titan is considered one of the most promising places to search for prebiotic chemistry.');

-- Ganymede
INSERT INTO factoids (object_id, content) VALUES
('ganymede', 'Ganymede is the largest moon in the solar system, bigger than the planet Mercury.'),
('ganymede', 'Ganymede is the only moon known to have its own magnetic field.'),
('ganymede', 'Ganymede likely has a subsurface saltwater ocean beneath its icy crust.'),
('ganymede', 'Ganymede''s surface has two types of terrain: ancient dark regions and younger grooved terrain.'),
('ganymede', 'Ganymede was discovered by Galileo Galilei on January 7, 1610.'),
('ganymede', 'Ganymede has a thin oxygen atmosphere — too thin to breathe.'),
('ganymede', 'Ganymede''s diameter is 5,268 km, about 8% larger than Mercury.'),
('ganymede', 'Ganymede is tidally locked to Jupiter, always showing the same face.'),
('ganymede', 'ESA''s JUICE mission launched in 2023 and will orbit Ganymede in the 2030s.'),
('ganymede', 'Ganymede''s subsurface ocean may be sandwiched between layers of ice.'),
('ganymede', 'Ganymede has auroras caused by its own magnetic field interacting with Jupiter''s.'),
('ganymede', 'Ganymede''s surface is a mix of ice and rock, heavily cratered in some areas.'),
('ganymede', 'Ganymede''s internal heat may come from tidal interactions with Jupiter and its other moons.'),
('ganymede', 'Ganymede is named after a beautiful youth in Greek mythology who became cupbearer to the gods.'),
('ganymede', 'Ganymede, along with Io, Europa, and Callisto, is one of the four Galilean moons.');

-- Europa
INSERT INTO factoids (object_id, content) VALUES
('europa', 'Europa''s icy surface hides a global saltwater ocean that may contain more water than all of Earth''s oceans.'),
('europa', 'Europa''s surface is one of the smoothest in the solar system, with very few large craters.'),
('europa', 'Europa is considered one of the best candidates for finding extraterrestrial life.'),
('europa', 'Europa''s ocean is kept liquid by tidal heating from Jupiter''s immense gravity.'),
('europa', 'Europa''s ice shell is estimated to be 10–30 km thick.'),
('europa', 'The cracks on Europa''s surface suggest the ice shell floats freely on the ocean below.'),
('europa', 'Europa was discovered by Galileo Galilei in 1610.'),
('europa', 'NASA''s Europa Clipper mission launched in 2024 to study Europa''s habitability.'),
('europa', 'Europa is about the size of Earth''s Moon.'),
('europa', 'Plumes of water vapour may erupt from Europa''s surface, similar to Enceladus.'),
('europa', 'Europa''s surface is relatively young — only about 20–180 million years old based on crater counts.'),
('europa', 'Europa''s reddish-brown streaks may be salts and sulphur compounds from the ocean below.'),
('europa', 'Europa orbits Jupiter in about 3.5 Earth days.'),
('europa', 'Europa is named after a Phoenician princess in Greek mythology who was abducted by Zeus.'),
('europa', 'Europa''s subsurface ocean may have hydrothermal vents similar to those on Earth''s ocean floor.');
