export const WEATHER_CONFIG = {
  // Coefficients
  REFRACTION_COEFFICIENT: 4 / 3,
  BETA_BASE: 0.05, // Clear air baseline
  BETA_CLOUD_MULTIPLIER: 0.5,
  BETA_PRECIPITATION_MULTIPLIER: 0.1,
  BETA_FOG_MULTIPLIER: 20,

  // Thresholds
  TROPICAL_LATITUDE: 23.5,
  DESERT_LAT_MIN: 15,
  DESERT_LAT_MAX: 35,
  DESERT_LON_MIN: 0,
  DESERT_LON_MAX: 60,

  // PRNG
  SEED_MULTIPLIER_1: 9301,
  SEED_ADDEND: 49297,
  SEED_MODULO: 233280,
} as const

export const MAP_CONFIG = {
  // Map Bounds
  MIN_ZOOM: 2,
  MAX_ZOOM: 10,
  DEFAULT_ZOOM: 4,
  TILE_SIZE: 256,
  
  // Bounds Calculation
  LON_THRESHOLD: 300,
  LAT_THRESHOLD: 160,
  MAX_LAT: 85,
  MIN_LAT: -85,
  MAX_LON: 180,
  MIN_LON: -180,

  // Overlay
  TIME_BUCKET_MINUTES: 5,
  SAMPLES_LOW: 64,
  SAMPLES_MEDIUM: 96,
  SAMPLES_HIGH: 128,
  ZOOM_LOW_THRESHOLD: 3,
  ZOOM_HIGH_THRESHOLD: 7,
} as const

export const VISIBILITY_CONFIG = {
  EARTH_RADIUS_KM: 6371,
  HORIZON_FACTOR: 3.57,
  KOSCHMIEDER_CONSTANT: 3.912,
} as const

export const TIME_CONFIG = {
  // Hours (0-23)
  DAY_START: 6,
  DAY_END: 20,
  DAWN_START: 5,
  DAWN_END: 6,
  DUSK_START: 20,
  DUSK_END: 21,
  TWILIGHT_AM_START: 4,
  TWILIGHT_AM_END: 5,
  TWILIGHT_PM_START: 21,
  TWILIGHT_PM_END: 22,

  // Factors
  FACTOR_DAY: 1.0,
  FACTOR_DAWN_DUSK: 0.7,
  FACTOR_TWILIGHT: 0.5,
  FACTOR_NIGHT: 0.3,
} as const
